sudo: required
dist: trusty

services:
  - docker

language:
    - cpp

compiler:
    - gcc
    - clang

before_install:
    # Add software package repositories with recent versions of boost
    - sudo add-apt-repository ppa:afrank/boost --yes
    - sudo apt-get update -qq

install:
    # Install mfast dependencies
    - sudo apt-get install -qq libboost1.57-all-dev

script:
    - mkdir _build
    - cd _build
    - cmake ..
    - make
    - make test
    - if [ $CC == "clang" ]; then cd .. && ./emscripten_build.sh; fi

# whitelist
branches:
  except:
    - gh-pages
    - emdi